home(contextPath) ::= "
<div class='simplicity'>
	<div class='container'>
		<div class='col-sm-12'>
			This is home page <br/>
			This is home page <br/>
			Conflicting ahead of us. <br/>
			This is home page <br/>
			cham change this.<br/>
            <div class='btn-group'>
                <a href='$contextPath$test/' class='btn btn-danger' role='button'>test</a>
                <a href='$contextPath$login.html' class='btn btn-success'role='button'>login page</a>
                <a href='$contextPath$form.html' class='btn btn-info' role='button'>Upload File</a>
            </div>
        </div>
    </div>
</div>
";